# Generated by Django 4.1.3 on 2022-11-26 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField()),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_department', models.CharField(max_length=50)),
                ('emp_salary', models.FloatField()),
                ('emp_tasks', models.IntegerField()),
                ('emp_manager', models.CharField(max_length=50)),
            ],
        ),
    ]
